#!/bin/sh

compton &

polybar example &

pkill -9 xscreensaver
xscreensaver -no-splash &

xsetroot -cursor_name crosshair &

bspc config urgent_border_color "#FB4934"
bspc config presel_border_color "#458588"
bspc config normal_border_color "#232323"
bspc config focused_border_color "#000000"

xwallpaper &

