#!/bin/sh

export THEME='mosh'

polybar example &

bspc config border_width    4

bspc config window_gap     64

bspc config urgent_border_color "#FFFFFF"
bspc config presel_border_color "#458588"
bspc config normal_border_color "#232323"
bspc config focused_border_color "#BBBBBB"

feh --bg-scale Pictures/Wallpaper/waves-mosh.jpg

