#!/bin/sh

export THEME='purple'

compton &

polybar example &

#pkill -9 xscreensaver
#xscreensaver -no-splash &

xsetroot -cursor_name crosshair &

bspc config border_width    4
bspc config window_gap     28

bspc config top_padding    50
bspc config bottom_padding 18
bspc config left_padding   18
bspc config right_padding  18

bspc config urgent_border_color "#FB4934"
bspc config presel_border_color "#000000"
bspc config normal_border_color "#4D1E5F"
bspc config focused_border_color "#D0B4D1"

feh --bg-scale Pictures/Wallpaper/mavericks-2.jpg
#xwallpaper &

alacritty="alacritty --config-file ~/.config/alacritty/purple.yml"

