#!/bin/sh

export THEME='reset'

pkill -9 polybar
pkill -9 compton
pkill -9 xwinwrap
pkill -9 feh

bspc config border_width   2
bspc config window_gap     0
bspc config top_padding    0
bspc config bottom_padding 0
bspc config left_padding   0
bspc config right_padding  0

