#! /bin/sh

sxhkd &

xscreensaver -no-splash &

xfce4-power-manager --no-daemon &

#Mouse Cursor (/usr/share/icons/DMZ-White/cursors)
#xsetroot -cursor_name crosshair &
#nomouse
#sudo xinput set-prop 11 "Device Enabled" 0 # or 1

bspc monitor eDP1 -d I II III IV V
#bspc monitor HDMI-1 -d X

bspc config border_width         4
bspc config window_gap          28

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Steam desktop='^4'
bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a LG3D desktop='^3' state=floating follow=on
bspc rule -a Gpick state=floating follow=on
bspc rule -a Screenkey manage=off
bspc rule -a vlc state=floating rectangle=32x32+0x0 follow=on sticky=on
bspc rule -a feh state=floating rectangle=32x32+0x0

bspc config top_padding        50 #18 + 32
bspc config bottom_padding     18
bspc config left_padding       18
bspc config right_padding      18

pointer_action2 resize_corner
pointer_action3 focus

#setxkbmap -option caps:escape

#load theme
./.config/themes/$THEME

