#! /bin/sh

xset +fp /home/james/.fonts
xset fp rehash

sxhkd &

compton &

polybar example &

feh --bg-scale ~/Pictures/MOSHED-2019-1-31-14-21-13.jpg

xrandr --output eDP-1 --brightness 1.0

bspc monitor eDP-1 -d I II III IV V VI VII VIII IX
bspc monitor HDMI-1 -d X

#bspc config border_width         6
#bspc config window_gap          24
bspc config border_width         6
bspc config window_gap          30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Rhythmbox desktop='^9'
bspc rule -a Steam desktop='^8'
bspc rule -a Gimp desktop='^7' state=floating follow=on
#bspc rule -a Google Chrome desktop='^2'
bspc rule -a Screenkey manage=off

bspc config normal_frame_opacity 0.75
bspc config focused_frame_opacity 0.75

bspc config top_padding        18
bspc config bottom_padding     18
bspc config left_padding       18
bspc config right_padding      18

#bspc config normal_border_color "#484848"
#bspc config focused_border_color "#1F8999"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

bspc config normal_border_color "#222222"
bspc config focused_border_color "#BDAE93"


gnome-terminal -x bash -c "cmatrix -C cyan"
#gnome-terminal -x bash -c "tty-clock -C 6 -s -c"
#gnome-terminal -x bash -c "htop"
gnome-terminal -x bash -c "ncmpcpp"
gnome-terminal -x bash -c "newsbeuter"

amixer sset Master 100+ unmute
amixer sset Headphone 100+ unmute
amixer sset Speaker 100+ unmute

