#! /bin/sh

sxhkd &

compton &

feh --bg-scale ~/Pictures/MOSHED-2019-1-31-14-21-13.alt.jpg

xrandr --output eDP-1 --brightness 1.0

bspc monitor eDP-1 -d I II III IV V VI VII VIII IX
bspc monitor HDMI-1 -d X

#bspc config border_width         6
#bspc config window_gap          24
bspc config border_width         6
bspc config window_gap          30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Steam desktop='^8'
bspc rule -a Gimp desktop='^7' state=floating follow=on
bspc rule -a Screenkey manage=off

bspc config normal_frame_opacity 0.75
bspc config focused_frame_opacity 0.75

bspc config top_padding        18
bspc config bottom_padding     18
bspc config left_padding       18
bspc config right_padding      18

bspc config urgent_border_color "#B58900" #todo
bspc config presel_border_color "#26E2FF" #todo
bspc config normal_border_color "#222222"
bspc config focused_border_color "#BDAE93"


gnome-terminal -x bash -c "cmatrix"
gnome-terminal -x bash -c "htop"
gnome-terminal -x bash -c "newsbeuter"

#amixer sset Master 100+ unmute
#amixer sset Headphone 100+ unmute
#amixer sset Speaker 100+ unmute

polybar example &

